
# We need sudo permissions
sudo: required

# tell Travis we need a copy of docker running
services:
  - docker

# Build our TEST image for React module
before_install:
  # Provide a tag name because we don't have an easy way to grab image id.
  # Given name won't matter too much because it's just an internal name
  # ---however, meaninful naming is a best-practice	
  - docker build -t errrzarrr/fibo-client-test -f Dockerfile.dev ./client

# Tell Travis how to run our test suite
script: 
  - docker run -e CI=true errrzarrr/fibo-test npm test 

# build PRODUCTION versions of each module
after_success:
  - docker build -t errrzarrr/fibo-client ./client
  - docker build -t errrzarrr/fibo-nginx  ./nginx
  - docker build -t errrzarrr/fibo-server ./server
  - docker build -t errrzarrr/fibo-worker ./worker
  # push it all to hub.docker.com
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  
  - docker push errrzarrr/fibo-client
  - docker push errrzarrr/fibo-nginx 
  - docker push errrzarrr/fibo-server
  - docker push errrzarrr/fibo-worker
