
# We need sudo permissions
sudo: required

# tell Travis we need a copy of docker running
services:
  - docker

# Build our TEST image for React module
before_install:
  # Provide a tag name because we don't have an easy way to grab image id.
  # Given name won't matter too much because it's just an internal name
  # ---however, meaninful naming is a best-practice	
  - docker build -t errrzarrr/fibo-client-test -f ./client/Dockerfile.dev ./client

# Tell Travis how to run our test suite
script: 
  - docker run -e CI=true errrzarrr/fibo-client-test npm test 

# build PRODUCTION versions of each module
after_success:
  - docker build -t errrzarrr/fibo-client ./client
  - docker build -t errrzarrr/fibo-nginx  ./nginx
  - docker build -t errrzarrr/fibo-server ./server
  - docker build -t errrzarrr/fibo-worker ./worker
  # push it all to hub.docker.com
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  
  - docker push errrzarrr/fibo-client
  - docker push errrzarrr/fibo-nginx 
  - docker push errrzarrr/fibo-server
  - docker push errrzarrr/fibo-worker
deploy:
  # VPS or cloud provider, like DO, AWS or heroku 
  provider: elasticbeanstalk 
  region: "us-east-2"
  # AWS' EB instance (application) name
  app: "fibo" 
  # environment name in that application
  env: "Fibo-env" 
  # S3 bucket created automatically for you for that region
  bucket_name: "$AWS_S3_BUCKET" 
  # same as app name, usually
  bucket_path: "fibo" 
  on:
    # deploy only features that were merged into 'master' branch
    branch: master
  access_key_id: 
    secure: "$AWS_PUBLIC_KEY"
  # WARNING: AWS will only show you it once and no more
  secret_access_key:
    secure: "$AWS_PRIVATE_KEY"
   